concord-consortium/geniblocks

gv2/case-3/case-3-challenge.js
gv2/case-3/case-3.js
gv2/case-3/index.html
gv2/index.html

Add Case3 component wrapping Case3Challenge component to handle navigation
Separate Case3Challenge component (and subcomponents) into a separate file

Case3 navigation

---

gulp/tasks/browserify-task.js
gv2/case-5/case-5.js
package.json
src/code/components/button.js
src/code/components/modal-alert.js
src/code/geniblocks.js

- Add ModalAlert component to GeniBlocks (based on react-overlays) [#118013601]
- Replace browser alerts in Case 5 with ModalAlerts [#118014069]
- Upon completion of challenge, users can Try Again or return to Case Log [#118014069]

Improve Case 5 feedback dialogs and navigation

---

examples/basic-examples/genome-test.html
gv2/case-3/challenge.js
gv2/gv2.js
package.json
src/code/components/modal-alert.js

- Build with babel-polyfill which should help with IE support
- Eliminate React warnings

Add babel polyfill and fix ESLint issues

---

gv2/case-1/case-1.js
gv2/case-1/challenge.js
gv2/cc-logger.js
gv2/event.js
gv2/gv2.js
package.json
readme.md

- Add CCLogger component to GV2
- Add logEvent() calls in Case 1
- Addresses  [#118505559]

Add logging infrastructure to GV2; log events in Case 1

---

package.json
src/code/components/basket-set.js
src/code/components/egg-clutch.js
src/code/components/egg-hatch.js
src/code/hoc/animate-spring.js
src/code/hoc/initial-element-id.js
src/code/hoc/target-element-id.js
src/code/hoc/update-on-resize-scroll.js
src/code/hoc/update-on-resize.js
src/code/templates/egg-sort-game.js

Support dynamic computation of DOM target locations [#132334089]
Eliminate support for hatching drake in egg in clutch
Use higher-order components to simplify animation code
Move animatedComponents array into component state

More robust animation implementation

---

examples/index.html
package.json
src/code/components/basket-set.js
src/code/components/egg-clutch.js
src/code/components/egg-hatch.js
src/code/templates/egg-sort-game.js
src/code/utilities/trial-generator.js
src/resources/authoring/gv2.js
src/stylus/challenges.styl

Drakes/eggs specified explicitly in authoring and presented randomly
Add specification of Case 4:
- trial 1 (horns)
- trial 2 (armor)
- trial 3 (horns/wings/armor)

Egg Game III: Authoring improvements and Case 4

---

examples/index.html
src/code/actions.js
src/code/containers/challenge-container.js
src/code/reducers/helpers/load-state-from-authoring.js
src/code/reducers/index.js
src/code/templates/egg-game.js
src/code/templates/genome-challenge.js
src/code/utilities/lang/en-us.js
src/code/utilities/translate.js
src/resources/authoring/gv2.js
src/stylus/challenges.styl

- Support 'start' URL parameter which (if present) takes user to a specified URL at the end of each case [#133214085]
- Separate Egg Game I and Egg Game II into separate cases [#133214085]
- Add instructions banners to challenges without instructions [#133210847]
- Show user drake in first genome challenge [#133211375]
- Improve earned coin feedback message [#133209955]
- Fix scoring of Egg Game I
- "You have found..." => "You have earned..." [#133234077]
Since Sam's been getting more than his fair share of code reviews lately, I'm assigning this one to @dstrawberrygirl.

Changes to support the October classroom test

---

examples/index.html
src/code/actions.js
src/code/app.js
src/code/containers/authoring-upload.js
src/code/containers/challenge-container.js
src/code/reducers/helpers/load-state-from-authoring.js
src/code/reducers/index.js
src/code/templates/egg-game.js
src/code/utilities/genetics-utils.js
src/code/utilities/trial-generator.js
src/resources/authoring/gv2.json
src/stylus/authoring-upload.styl
test/utilities/genetics-utils.js

- Author configuration should be JSON not JavaScript. [#133187035]
- Support author=upload URL parameter which allows user to load authoring document for testing [#133187467]
- Egg games use new-style dash allele strings for authoring [#133194823]
- Validate user-specified route changes
- Egg Game II: Don't generate the same target drake twice [Trudi]
@sfentress You're the logical reviewer for this one. I'll give the next one to Chris.

Egg game authoring improvements

---

examples/index.html
src/code/actions.js
src/code/reducers/index.js
src/code/templates/egg-sort-game.js
src/code/utilities/genetics-utils.js
src/code/utilities/trial-generator.js
test/actions/change-basket-selection.js
test/actions/change-drake-selection.js
test/actions/egg-accepted.js
test/actions/egg-rejected.js
test/actions/navigate-to-challenge.js
test/actions/navigate-to-current-route.js
test/actions/submit-egg.js
test/templates/egg-game.js
test/templates/egg-sort-game.js
test/utilities/genetics-utils.js
test/utilities/trial-generator.js

Add unit tests for
- new GeneticsUtils functions
- alleleStringContainsAlleles()
- isValidAlleleString()
- isCompleteAlleleString()
- TrialGenerator
- all-combinations
- randomize-order
- Redux actions
- changeBasketSelection()
- changeDrakeSelection()
- acceptEggInBasket()
- rejectEggFromBasket()
- navigateToCurrentRoute()
- submitEggForBasket()
Sam got the last one, so this one's for @dstrawberrygirl.

Egg Game unit test improvements

---

examples/gv2-prototype/case-1/challenge.js
package.json
src/code/actions.js
src/code/components/animated-component.js
src/code/components/chromosome-image.js
src/code/components/gamete-image.js
src/code/components/gamete-pen.js
src/code/containers/challenge-container.js
src/code/reducers/gamete-pools.js
src/code/reducers/helpers/load-state-from-authoring.js
src/code/reducers/index.js
src/code/templates/egg-game.js
src/code/templates/egg-sort-game.js
src/code/utilities/repeat-timer.js
src/code/utilities/timer-set.js
src/index.html
src/resources/authoring/gv2.json
src/stylus/challenges.styl
src/stylus/gamete-pen.styl
yarn.lock

Implements the initial randomization/animation sequence which shows the formation of gametes from chromosomes:
For each chromosome pair of each parent:
- the selected chromosome initially alternates rapidly
- the pace of alternation slows before settling on a single chromosome (intended to evoke metaphor of slot machine animation)
- when a single chromosome is selected it animates to the half-genome in the center, as is true in other games when a chromosome is selected by the user
For each completed gamete of each parent:
- the chromosomes animate to the interior of the gamete image in the upper part of the screen
- then the entire gamete animates to the gamete pool at the bottom of the screen
The randomization/animation proceeds through the following stages, each of which produces one …

Formation of Gametes Game - Initial randomization/animation sequence [#136526365]

---

src/code/templates/egg-game.js

One more bit of code cleanup that was nagging at me after my last big PR.

Refactor resetAnimationEvents() to take single options argument

---

src/code/actions.js
src/code/containers/challenge-container.js
src/code/containers/fv-challenge-container.js
src/code/middleware/its-log.js
src/code/reducers/helpers/load-state-from-authoring.js
src/code/templates/egg-game.js
src/code/templates/fv-egg-game.js
src/code/templates/genome-challenge.js
src/code/utilities/genetics-utils.js
test/actions/submit-drake.js
test/templates/egg-game.js
test/templates/genome-challenge.js

Here are the changes we discussed for the ITS. I also added a utility function for a common conversion operation. Let me know if I can make any improvements!

Adding information to submitDrake action for ITS

---

src/code/containers/fv-challenge-container.js
src/code/fv-components/fv-gamete-image.js
src/code/fv-components/parent-drake.js
src/code/templates/fv-egg-game.js
src/stylus/challenges.styl
src/stylus/fablevision/breed-button.styl
src/stylus/fablevision/fv-chromosome.styl
src/stylus/fablevision/fv-gamete.styl
src/stylus/fablevision/fv-stable.styl
src/stylus/fablevision/parent-drake.styl

Apply top-level CSS scale factor to fit challenge in viewport
- adjust animation computations in FVEggGame to counteract effect of scale
- tweak layout of a number of other objects to work with scaling
- set top-level font size and specify other font-sizes in rem units

Layout C challenges respond reasonably to viewport size

---

src/code/actions.js
src/code/its-constants.js
src/code/middleware/its-log.js
src/resources/authoring/gv2.json
test/actions/submit-drake.js

Remaining small updates to get the ITS running

Adding more constants to ITS logs

---

src/code/app.js
src/code/middleware/its-log.js
src/code/reducers/notifications.js
src/resources/authoring/gv2.json

- Queue ITS messages sent before ITS connection established
- Send any queued messages once ITS connection established
- More consistent console.logging of ITS messages
- Dispatch SessionStarted message before any other messages (e.g. default first navigation)
- Dismissing feedback dialog in match drake challenge doesn't dismiss ITS message

ITS improvements

---

src/code/templates/fv-egg-game.js
src/stylus/fablevision/breed-button.styl

- Adjust color of disabled breed button text [##142003501]
- Reset gametes on new challenge

Final(?) tweaks

---

src/code/action-types.js
src/code/app.js
src/code/middleware/its-log.js
src/code/modules/notifications.js
src/code/reducers/index.js
src/code/reducers/modal-dialog.js
src/code/reducers/user-drake-hidden.js
test/actions/notifications.js
test/actions/show-modal-dialog.js

- create `notifications` module
- move ITS initialization into `its-log` module

ITS code refactor [#142098249]

---

src/code/action-types.js
src/code/actions.js
src/code/reducers/index.js

- advanceChallenge() action is redundant with navigateToNextChallenge()
- ADVANCED_CHALLENGE type is redundant with NAVIGATED_NEXT_CHALLENGE

Eliminate unused advanceChallenge() action

---

src/code/fv-components/breed-button-area.js
src/code/templates/fv-egg-game.js

Also, adjust ITS notification location

Fix retry mission stable bug

---

src/code/actions.js

Quick change to reduce popup noise on correct answers in egg sorting game

Removing modal dialog on correct egg placement [#142717227]

---

src/code/fv-components/fv-change-sex-toggle.js
src/stylus/fablevision/fv-change-sex-toggle.styl

Quick fix- now, you can click anywhere on the button to toggle it between male and female, rather than having to click the corresponding side. Also adding cursor hover to the whole toggle.

Fixing bug #144520521: sex only switches if you click on the empty space

---

src/resources/authoring/gv2.json

Updating the names of challenges in the authoring document, now that Trudi and I came up with consistent names which are referenced in the master document.
Not much to review here, I may merge without one

Updating challenge names to match master authoring document

---

bower.json
src/code/actions.js
src/code/app.js
src/code/middleware/its-log.js
src/code/modules/notifications.js
src/code/templates/fv-egg-sort-game.js
src/code/utilities/genetics-utils.js
src/resources/authoring/gv2.json
test/actions/submit-drake.js
test/actions/submit-egg.js
test/utilities/genetics-utils.js

@kswenson, I'm sending this over to you, since we had discussed the communication from GV2 to ITS a bit in person. Ultimately, we pushed the responsibility to the ECD matrices to use the constant string keys in BioLogica, so no large-scale changes were required here or in BioLogica, and all the matrices are up-to-date at this point. In the end, this PR is mostly re-organizing some information into the form that the ITS expects.

Egg Sorting ITS Upgrade

---

src/code/actions.js
src/code/containers/fv-challenge-container.js
src/code/containers/navigation.js
src/code/reducers/helpers/load-state-from-authoring.js
src/code/reducers/index.js
src/code/templates/fv-genome-challenge.js
src/code/templates/genome-challenge.js
src/resources/authoring/gv2.json
src/stylus/fablevision/fv-gene-label.styl
test/actions/submit-drake.js
test/templates/egg-game.js
test/templates/genome-challenge.js

This was already reviewed by @sfentress, just recreating the PR here on master instead of another side branch.

Color levels

---

src/code/fv-components/fv-egg-hatch.js
src/code/fv-components/fv-gene-label.js
src/code/templates/clutch-game.js
src/code/templates/fv-egg-game.js
src/stylus/challenges.styl
src/stylus/fablevision/fv-egg-clutch.styl
src/stylus/fablevision/fv-gene-label.styl
src/stylus/fablevision/fv-genome-challenge.styl
src/stylus/navigation.styl

Here are the style changes I made to make Geniverse work on iPads for the classroom test last week, which coincidentally fixed Safari use. A lot of the changes required copying default styles from Chrome into the actual CSS.
Note that I did intentionally base this off the `clutchLevels` branch - since I want to finish up that PR before merging this in, I'll handle all the merging into master once the PRs are done.

Making game usable on Safari and mobile browsers

---

src/code/actions.js
src/code/templates/fv-egg-sort-game.js
src/code/utilities/lang/en-us.js
src/stylus/fablevision/fv-egg-sort-game.styl
src/stylus/notifications.styl

Another quick review based on today's demo! Previously, drakes faded away immediately when the number of right or wrong answers changed, so there was no time to inspect the drake. Now, drakes don't disappear until another egg is clicked. I think the logic is easier to follow, but it did take me a few tries to get to this point, so please let me know what you think!

Fixing hatched egg display

---

src/code/components/chromosome.js
src/code/components/clutch-view.js
src/code/fv-components/bottom-hud.js
src/code/fv-components/fv-chromosome-image.js
src/code/fv-components/fv-stable.js
src/code/fv-components/gem-set.js
src/code/reducers/helpers/load-state-from-authoring.js
src/code/templates/clutch-game.js

There were a handful of React errors that were thrown in every game, which made catching actual errors much more difficult. I resolved every error I could find in this PR!

Fixing all console errors

---

src/code/hoc/scale-to-fit.js
src/resources/authoring/gv2.json
src/stylus/challenges.styl

Very quick changes: reverting centering update and randomizing colors in playground

UI updates

---

src/code/action-types.js
src/code/actions.js
src/code/modules/notifications.js
src/code/reducers/helpers/load-state-from-authoring.js
src/code/reducers/modal-dialog.js
src/code/reducers/user-drake-hidden.js
src/resources/authoring/gv2.json
src/stylus/notifications.styl
test/actions/notifications.js
test/actions/submit-drake.js

Dialog is now displayed at the end of each challenge, which depends on whether or not a gem was earned.

End challenge dialog

---

src/code/actions.js
src/code/components/notifications.js
src/code/fv-components/end-level-dialog.js
src/code/reducers/gems.js
test/actions/egg-rejected.js
test/actions/submit-egg.js

Fixes the "stranded user" bug from today, and cleans up feedback delivery order

Classroom bugfixes

---

src/code/reducers/gems.js
src/resources/authoring/gv2.json

Changs so last minute - going to get reverted post-test anyway

Hiding nucleus levels and fixing out of order levels bug

---

src/code/actions.js
src/code/components/notifications.js
src/stylus/notifications.styl
test/actions/submit-drake.js

This makes the dialog popups styled differently for hints and ITS messages vs narrative text.

Add its-style to messages that are not narrative

---

src/code/reducers/helpers/load-state-from-authoring.js
src/code/templates/clutch-game.js
src/resources/authoring/trial-options.json
test/utilities/load-state-from-authoring.js

@dstrawberrygirl Last PR for now.
This lets us author different variations for trials.

Trial options

---

bower.json
src/code/components/tutorial-view.js
src/code/containers/fv-challenge-container.js
src/code/fv-components/bottom-hud.js
src/code/fv-components/counter.js
src/code/fv-components/fv-gene-label.js
src/code/fv-components/navigation-dialog.js
src/code/modules/tutorials.js
src/code/reducers/helpers/load-state-from-authoring.js
src/code/reducers/parent-drake-hidden.js
src/code/templates/fv-genome-challenge.js
src/code/utilities/progress-utils.js
src/resources/authoring/gv-1.json
src/stylus/fablevision/fv-gene-label.styl
src/stylus/fablevision/fv-genome-challenge.styl
test/templates/clutch-game.js
test/utilities/load-state-from-authoring.js

Initial implementation of level 6 challenges
- challenges 1-2 are visible target drake matching [#157981208]
- challenges 3-4 are hidden target drake matching [#157981248]
Fix layout issues with layout A challenges encountered in level 6 [#157981432]
- center genome layout within its borders
- fix layout of "non-standard" allele names (e.g. "tk")
- capitalize "MISSION" in bottom HUD for consistency with other labels
- fix React PropTypes warning when number of moves is exhausted
Fix ESLint warnings/errors
Note: This PR depends on the latest BioLogica PRs (0.11). Testing is likely to yield unexpected results without the latest BioLogica updates.

Level 6 Challenges 1-4

---

src/stylus/fablevision/fv-egg-sort-game.styl

Increase size of clickable area for baskets [#158155641]

Increase size of clickable area for baskets

---

src/resources/authoring/authoring.schema.json
src/resources/authoring/gv-1.json

[#158160253] Eliminate A2 allele from level 6 drakes

Eliminate A2 allele from level 6 drakes

---

src/code/components/organism.js
src/code/containers/challenge-container.js
src/code/containers/fv-challenge-container.js
src/code/fv-components/egg-hatch-drake.js
src/code/reducers/helpers/load-state-from-authoring.js
src/code/templates/fv-genome-challenge.js
src/resources/authoring/authoring.schema.json
src/resources/authoring/gv-1.json
src/stylus/fablevision/egg-hatch-drake.styl
src/stylus/fablevision/fv-genome-challenge.styl
test/components/organism.js

On top of the initial request I also added alt text to all drake images since we had the data readily-available to be added in a human-friendly form in case a drake image fails to load for some reason.

Add color labels to drakes on color challenges

---

src/code/fv-components/breed-button.js

Fixing another issue encountered while working on level 6 challenges.

Fix React warning about calling setState on unmounted component

---

package.json
script/templates.js

While working on the level 6 challenges, I frequently found myself searching through the authoring file to figure out which templates were used in which challenges with which configurations, so I modified one of our authoring-processing scripts to output that information in an easier-to-digest fashion:
```
Authoring File: src/resources/authoring/gv-1.json
Git Branch: templates-script
Export Date: 2018-06-07 09:03:11
Challenge 1.1.1 - [FVGenomeChallenge: create-unique] 'allele-5drakes-tutorial'
Challenge 1.2.1 - [FVGenomeChallenge: match-target] 'allele-targetMatch-visible-simpleDom'
Challenge 1.2.2 - [FVGenomeChallenge: match-target] 'allele-targetMatch-visible-simpleDom2'
Challenge 1.2.3 - [FVGenomeChallenge: match-target] 'allele-targetMatch-hidden-simpleDom'
Challenge 1.2.4 - …
```

Add `templates` script for listing challenges, templates, challengeTypes, etc.

---

readme.md
src/code/templates/fv-egg-game.js
src/resources/authoring/authoring.schema.json
src/resources/authoring/gv-1.json

- Add FVEggGame challenge to schema
- Add support for parent randomization via `randomMatched` capability to FVEggGame
- Add challenges 6.3.1 and 6.3.2 to authoring [#157981337]
Will need to confirm parent drakes with Trudi.

Implement Mission 6.3

---

src/code/modules/gametes.js
src/code/templates/fv-egg-game.js
src/resources/authoring/authoring.schema.json
src/resources/authoring/gv-1.json

FVEggGame supports target drake constraints, so sex or particular alleles can be specified
- constrain challenge 6.3.1 targets to be male
Add additional parent drake randomization
Reset gametes on navigation

Mission 6.3 enhancements

---

src/code/middleware/its-log.js
src/code/middleware/state-save.js
src/code/modules/notifications.js
src/code/utilities/firebase-auth.js
test/actions/notifications.js

Commenting out sections of ITS connectivity to ensure the students can play through end-to-end

Dragon camp - hide hints and fix Firebase issues

---

src/code/middleware/its-log.js
src/code/reducers/index.js
src/resources/authoring/gv-1.json
test/actions/submit-drake.js

Implement additional pieces to get hints working on breeding and egg drop challenges

ITS hint changes for egg drop and clutch games

---

src/code/templates/fv-egg-game.js

This was due to hatchSoundPlayed not resetting between levels

Consecutive egg games had  an incorrect move count

---

src/code/templates/clutch-game.js
src/resources/authoring/gv-1.json

Add move counter to sibling pair challenges [#158931996]

Add move counter to sibling pair challenges

---

package-lock.json
package.json

- update axios to 0.19.0
- eliminate unused growl dependency

Fix security vulnerability warning: axios

---

src/resources/authoring/gv-1.json

Challenge 2.2.2: 3-armor => 5-armor instead of the reverse

Fix challenge 2.2.2 to be more consistent with narrative text

---

.travis.yml
src/code/app.js

Provide additional `itsInstance` configuration options (default to CC ITS server for staging)
- `ncsu`, `production`, `ncsuProduction` => NCSU production ITS server (default)
- `ncsuStaging` => NCSU staging ITS server
- `cc`, `ccProduction` => CC production ITS server
- `staging`, `ccStaging` => CC staging ITS server (default for `/branch/staging`)

ITS configuration: support additional itsInstance options

---

gulp/tasks/default.js
gulp/tasks/deploy.js
gulp/tasks/examples-task.js
gulp/tasks/geniblocks-css-task.js
gulp/tasks/geniblocks-js-task.js
gulp/tasks/geniblocks-rsrc-task.js
gulp/tasks/trim-trailing-spaces.js
gulp/tasks/vendor-task.js
gulpfile.js
package-lock.json
package.json
readme.md

Update to Gulp 4

---

.travis.yml
package-lock.json
package.json
src/code/app.js
src/code/middleware/gv-log.js
src/code/middleware/its-log.js

[[#184539865]](https://www.pivotaltracker.com/story/show/184539865)
This small PR mostly updates URLs to point to the AWS servers, letting us move away from Heroku.

Update logging server and ITS server URLs
