concord-consortium/geniblocks

- examples/case-3/case-3.js
- src/code/components/glow-background.js
- src/code/components/organism.js
- src/code/components/pen-stats.js
- src/code/components/pen.js
- test/components/organism.js
- test/components/pen.js
- Dragging works on Firefox (but must select first)
- DragImage is the drake on all tested browsers
- Click selection/deselection works as expected
- Mitigates [#117663369]
- Fixes [#117663015]
> Mitigate case 3 browser drag/drop inconsistencies

- package.json
- src/code/actions.js
- src/code/app.js
- src/code/containers/challenge-container.js
- src/code/containers/modal-message-container.js
- src/code/middleware/router-history.js
- src/code/reducers/loadStateFromAuthoring.js
- src/code/reducers/reducer.js
- test/actions/navigate-to-challenge.js
This adds hash-based url routing for challenges.
* Case and challenge are visible in the url, starting at 1 to match expectations, as {geniblocks-url}/#/1/2 for case 1 challenge 2
* When the game is loaded, if no route is in the url, it will go to case 1 challenge 1 automatically
* If a url such as http://localhost:8080/#/1/3 is loaded directly, it will go directly to that challenge
* While in game, navigation button actions update the url
* While in game, you can change url route and it will be as if a navigation event happened in-game (i.e. an action is sent, and state changes as expected)
The loading of authored state was also simplified a tiny bit, it's now only called within a navigation action, so buttons or templates shouldn't need to call `loadAuthoredChallenge` anymore. A bit …
> Redux router

- examples/index.html
- package.json
- readme.md
Request from Frieda [9:31 AM]  
It would be great to have the new challenges that are available by URL (e.g., http://concord-consortium.github.io/geniblocks/gv2/#/2/1) added to the geniblocks examples page (http://concord-consortium.github.io/geniblocks/examples/) under a new category; how about "GV 2.0 Interactives"?
> Link to gv2 from examples

- examples/index.html
- src/code/actions.js
- src/code/components/challenge-award.js
- src/code/components/genome.js
- src/code/components/modal-alert.js
- src/code/components/ordinal-organism.js
- src/code/components/organism.js
- src/code/containers/challenge-container.js
- src/code/geniblocks.js
- src/code/reducers/helpers/load-state-from-authoring.js
- src/code/reducers/index.js
- src/code/reducers/routing.js
- src/code/reducers/user-drake-hidden.js
- src/code/templates/egg-game.js
- src/code/utilities/lang/en-us.js
- src/resources/authoring/gv2.js
- src/stylus/challenges.styl
- src/stylus/ordinal-organism.styl
- test/actions/navigate-to-challenge.js
- test/actions/submit-drake.js
- author can specify challenge type ("create-unique" or "match-target")
- author can specify whether user drake is hatched/shown automatically
- target drake is shown (and pen view is hidden) in target matching challenges [#129879003]
- user can fertilize once gametes are complete [#129879183][#129879515]
- egg hatches (Egg Game 2a) or not (Egg Game 2b) [#129879183][#129879515]
- after fertilization user can submit drake or reset gametes [#129879109]
- dialog gives feedback on whether submitted drake matches [#129879109]
- drake is visible while feedback dialog is displayed
- Egg Game 2a (hatched drake) and 2b (unhatched egg) each contain three trials
- gold, silver, or bronze coin piece provided upon completion of challenges [#120794161]
With 20/20 hindsight, it might have made sense to …
> Egg Game II

- package.json
- src/code/actions.js
- src/code/app.js
- src/code/components/notifications.js
- src/code/containers/notification-container.js
- src/code/middleware/its-log.js
- src/code/reducers/index.js
- src/code/reducers/modal-dialog.js
- src/code/reducers/notifications.js
- src/code/reducers/user-drake-hidden.js
- src/code/utilities/guide-protocol.js
- src/stylus/notifications.styl
- test/.eslintrc.json
- test/actions/notifications.js
- test/actions/show-modal-dialog.js
- yarn.lock
This fixes our communication to the ITS GUIDE Server, listens for ITS messages in their new format, and appends new messages to a new lightweight notification component.
Because the ITS messages are mostly demo strings for now, we don't show the messages by default. We can view the messages by including `?showITS=true` in the url. Eventually, we'll want to switch it so that the default is to view them.
https://www.pivotaltracker.com/story/show/137109565
https://www.pivotaltracker.com/story/show/137371291
> Fix GUIDE socket.io connection; show ITS messages

- src/code/reducers/helpers/load-state-from-authoring.js
- src/resources/authoring/gv2.json
- test/templates/egg-game.js
- test/templates/genome-challenge.js
This adds the ability to include
```
"linkedGenes": {
"drakes": [0, 1],
"genes": "tail, horns, color, black, dilute, armor, nose, bogbreath"
}
```
in the authoring, to define genes may not be explicitly authored, but must remain identical between two (or more) drakes.
https://www.pivotaltracker.com/story/show/136137281
> Authored linked genes

- examples/basic-examples/chromosomes.html
- examples/basic-examples/genome-test.html
- examples/basic-examples/genome.html
- examples/experiments/meiosis/meiosis.js
- src/code/components/allele-filters.js
- src/code/components/animated-gamete.js
- src/code/components/chromosome.js
- src/code/components/fertilizing-gamete.js
- src/code/components/gamete-pool.js
- src/code/components/gamete.js
- src/code/components/genome-test.js
- src/code/components/genome.js
- src/code/containers/challenge-container.js
- src/code/reducers/helpers/load-state-from-authoring.js
- src/code/reducers/index.js
- src/code/templates/egg-game.js
- src/code/templates/egg-sort-game.js
- src/code/templates/genome-challenge.js
- src/code/templates/genome-playground.js
- src/code/utilities/genetics-utils.js
- src/resources/authoring/gv2.json
- test/components/allele-filters.js
- test/components/chromosome.js
- test/components/genome-test.js
- test/utilities/genetics-utils.js
This replaces `hiddenAlleles` across GeniBlocks with `userChangeableGenes` and `visibleGenes`, which specify, using gene names, genes which the user may modify (if the view allows) and additional genes that the user can see.
Updated GB example components, tests, and authoring.
https://www.pivotaltracker.com/story/show/137548373
> Changeable visible genes

- examples/basic-examples/chromosomes.html
- src/code/components/chromosome.js
- src/code/components/gene-label.js
- src/code/components/genome.js
- src/code/containers/challenge-container.js
- src/code/reducers/helpers/load-state-from-authoring.js
- src/code/reducers/index.js
- src/code/templates/genome-challenge.js
- src/code/templates/genome-playground.js
- src/resources/authoring/gv2.json
- test/components/gene-label.js
Adds support for `hiddenAlleles` property, which now refers to explicit alleles (not as a short-hand for genes) to prevent certain options from being shown in gene pull-down menus.
This also demos the new biologica.js feature, which is authoring genes with limited-choice selection between alleles, e.g. `T/t-T/t`, which would leave out the `Tk` allele.
> Hidden alleles

- src/code/reducers/helpers/load-state-from-authoring.js
- src/code/templates/genome-challenge.js
- src/resources/authoring/gv2.json
- test/templates/egg-game.js
- test/templates/genome-challenge.js
This adds a generic way to randomize trials whenever an author is creating a list of predefined trials (e.g. the targetDrakes list for the genomeChallenge). It works by creating a shuffled array of trial-numbers, and passing that value in, instead of the actual trial number, whenever we use the trial number to calculate state (currently just in `authoredDrakesToDrakeArray`).
This also adds the ability to define an array of initial drakes for the genome challenge.
> Randomize trials

- examples/index.html
- src/code/components/gamete-pen.js
- src/code/reducers/helpers/load-state-from-authoring.js
- src/code/templates/egg-game.js
- src/resources/authoring/gv2.json
- src/stylus/challenges.styl
@sfentress Final commit added which wraps up all existing stories (to this point). You should be able to just review the most recent commits since you last reviewed the code.
Update: most recent commits wrap up basic functionality that was missing at the point the PR was first submitted:
- gametes are generated at the beginning of each trial/challenge and animation just syncs to pre-generated gametes
- generated gametes are guaranteed to include ones that can match the target
- gamete counts can be specified on a per-trial basis
- gamete counts are specified as integers rather than sets of `{}`s
- if there's only one gamete for a given parent it is selected automatically
@sfentress You may review the changes at your convenience.
Add challenges to authoring document
- Dragon 3.1: Draco …
> Fertilize the Egg game

- src/code/actions.js
- src/code/containers/challenge-container.js
- src/code/reducers/drakes.js
- src/code/reducers/helpers/load-state-from-authoring.js
- src/code/templates/egg-game.js
- src/code/templates/genome-playground.js
- src/code/utilities/genetics-utils.js
- src/resources/authoring/gv2.json
- test/actions/change-sex.js
- test/actions/keep-offspring.js
- test/templates/egg-game.js
- test/templates/genome-challenge.js
@kswenson @sfentress These commits first change the "sandbox" tutorial level into a "create 5 drakes" level which includes a drake pen. This change uses many of the same actions as the other template which includes a pen- the main difference is that here the baby drake is not removed when it is added to the pen.
The other fix is to address issues with sex-linked traits changing as a dragon's sex is changed. Now, as in GV1.0, when a drake changes from female to male, it records any alleles it is losing in the Redux state. When the drake changes from male to female, it restores any alleles so that it returns to the same state as the original female drake.
One difference from GV1.0 is that you can now fully specify an initial drake, regardless of its sex. By over-specifying a male (i.e. …
> Tutorial pen and consistent sex-linked traits

- src/stylus/challenges.styl
The playground's display was getting set to `block` by default, so here I'm forcing it to `flex` so it no longer wraps when the window becomes smaller (because of the `nowrap` property set elsewhere). I wanted to check that makes sense, and one more thing: most of the rules in this file use brackets for rules, but I can't seem to use the stylus-style indenting if I include them here. Is it ok to omit them?
> Preventing columns from wrapping in playground.

- src/resources/authoring/gv2.json
Not much to see here- I messed up the authoring order so I'm fixing it here, and updating the challenge names to match the new naming convention while I'm at it.
I also swapped out the Egg Game I/II/III names with more descriptive names (Egg Sorting Game and Egg Breeding Game). Would it be alright to use terms like those moving forward?
> Changing challenge order and names in authoring doc

- src/code/components/chromosome.js
- src/stylus/fablevision/fv-chromosome.styl
Simple fix to update chromosome labels to static text, switching on the `ChromosomeImageClass`
> Updating chromosome layouts to FV style

- package.json
- src/code/app.js
- src/code/containers/modal-message-container.js
- src/code/geniblocks.js
- src/stylus/fablevision/breed-button.styl
- src/stylus/fablevision/fv-stable.styl
- src/stylus/fablevision/parent-drake.styl
- yarn.lock
- add polyfills for IE11 support
- add text adjustments for all Windows browsers
All Windows browsers tested (Chrome, Firefox, IE11) showed the same text offsets, suggesting that it may be a font-metrics issue rather than a browser issue. We "fix" it for the time being by user agent-sniffing for Windows and adding the `os-windows` class to the `<body>` tag if appropriate. Then CSS is used on a case-by-case basis to adjust the text where appropriate.
Note: after review, let me merge so I can rebase appropriately.
> Windows support

- src/code/components/notifications.js
- src/code/containers/notification-container.js
- src/code/fv-components/breed-button-area.js
- src/code/templates/fv-egg-game.js
- src/code/utilities/unscale-properties.js
For the classroom test, Frieda requested that the ITS feedback be placed next to the user user drake. Ultimately, we expect it to come from a character in the HUD, so this approach is temporary and will likely be removed after the classroom test.
Note: after review, let me merge so I can rebase appropriately.
> Move ITS notifications next to user drake [#142012501]

- src/code/middleware/gv-log.js
- logging enabled for non-development use by default
- logging disabled for development by default
- logging can be enabled for development by URL parameter
Note: I don't have access to the log manager, so I haven't been able to check what's being logged at the other end, but what's being sent from the client looks reasonable.
> Enable CC logging [#142012533]

- src/code/utilities/unscale-properties.js
- unscaling code must take scroll position into account
Note: although I'm tempted to try to get this in before tomorrow's classroom test, I think prudence suggests that we hold off on any more deployments unless a true showstopper is encountered.
> Fix animations when document is scrolled

- bower.json
- src/code/actions.js
- src/code/containers/challenge-container.js
- src/code/containers/fv-challenge-container.js
- src/code/reducers/modal-dialog.js
- src/code/templates/genome-playground.js
- src/stylus/challenges.styl
Fix a handful of issues in which changes for the new layout adversely affected old challenges. Some of these are layout issues, some are functionality.
- Redo some layout changes that adversely affected previous challenges in ways that don't have the adverse effects.
- Like regular guide messages, guide alert messages shouldn't dismiss dialogs before users have had a chance to read them
- Add null test for `visibleGenes` before dereferencing it
- Lock Biologia.js version at 0.0.2 to force usage of old allele strings
- User always gets gold coin for first playground level
Note: Currently depends on PR#89. This PR should be rebased once that one has been merged.
PR#89 has been merged and this PR has been rebased.
> Fix previous challenges

- src/code/app.js
- src/code/middleware/gv-log.js
- src/code/middleware/its-log.js
- `baseUser` defaults to "gv2-user" if URL parameter is not specified
- `userName` = "{baseUser}-{partialSessionID}"
- `userName` is constructed in app.js and passed to CC logger and ITS via `loggingMetadata`
Note: Currently depends on PR#89. This PR should be rebased once that one has been merged.
PR#89 has been merged and this PR has been rebased.
> Add baseUser URL parameter [#142141187]

- src/code/actions.js
- src/code/app.js
- src/code/containers/challenge-container-selector.js
- src/code/middleware/gv-log.js
- src/code/middleware/its-log.js
- src/code/reducers/helpers/load-state-from-authoring.js
- src/code/utilities/authoring-utils.js
- src/resources/authoring/gv2.json
- test/actions/egg-accepted.js
- test/actions/egg-rejected.js
- test/actions/navigate-to-challenge.js
- test/actions/navigate-to-current-route.js
- test/actions/submit-drake.js
- test/templates/egg-game.js
- test/templates/genome-challenge.js
Updated the authoring doc per this story:
https://www.pivotaltracker.com/story/show/142096149
The structure is now broken into level definitions and a level hierarchy. Additionally, at the suggestion of @kswenson, I use objects instead of strings in the level hierarchy so that we could move application-specific logic into the hierarchy and make the levels more reusable. The idea is that we could move more applications into a single authoring document, but I didn't have the opportunity to do that, and want to prioritize other tasks.
The downside of using objects instead of strings is that it makes the authoring document a little more challenging for non-engineers to modify. What do you think?
> Authoring restructure

- src/code/containers/challenge-container-selector.js
- use new `routeParams` in `componentWillReceiveProps` rather than `this.props.routeParams`
- add missing propType declaration for `challengeId` (in the neighborhood)
> Fix route navigation bug in PR#94

- package.json
- src/code/app.js
- src/code/geniblocks.js
- yarn.lock
`babel-polyfill`, which was added after `es6-object-assign`, includes its own polyfill for Object.assign().
> Eliminate redundant Object.assign() polyfill

- src/code/containers/fv-challenge-container.js
- src/code/hoc/scale-to-fit.js
For generalization to other layouts as well as for integration with drag/drop experimentation it is convenient to have the scaling code packaged as a reusable higher-order component (HOC) rather than integrated tightly with the `FVChallengeContainer`.
> Extract scaling into higher-order component (HOC) scaleToFit()

- package.json
- src/code/components/custom-drag-layer.js
- src/code/components/drag-organism.js
- src/code/components/organism.js
- src/code/containers/challenge-container-selector.js
- src/code/containers/fv-challenge-container.js
- src/code/fv-components/fv-drop-stable.js
- src/code/fv-components/fv-stable.js
- src/stylus/fablevision/fv-drop-stable.styl
- yarn.lock
- add DragDropContext to ChallengeContainerSelector
- add DragOrganismView to support dragging of drakes
- add FVDropStableView to support dropping of drakes in the stable
- add CustomDragLayer for IE11/touch backend support
- outline stable in yellow when drag is in progress (for demonstration only)
- outline stable in green when drag is over stable (for demonstration only)
This PR depends on the [`scaleToFit` PR#108](https://github.com/concord-consortium/geniblocks/pull/108) and should be rebased once that PR is merged.
This PR was not originally intended for merging at this point. It was part of an investigation to determine what would be involved to support drag/drop in GV2 given the scaling that we are doing as well as the platform support issues of the React-DnD library. The …
> Support dragging a drake to the stable (#142262279)

- gulp/config.js
- gulp/tasks/default.js
- New/deleted files now trigger rebuilds (add `{ cwd: './' }` argument) [#142103931]
- ~~`watch-fast` task now watches `resources` directory~~
Having `watch-fast` watch the `resources` directory turned out to be problematic because the resources task copies the entire resources folder which is slow and triggers excessive numbers of reloads, so it has been removed from this PR.
> Fix gulp.watch issues

- src/code/actions.js
- src/code/app.js
- src/code/containers/fv-challenge-container.js
- src/code/middleware/its-log.js
- src/code/modules/gametes.js
- src/code/templates/fv-egg-game.js
- test/actions/submit-egg.js
- test/modules/gametes.js
A handful of different ITS updates:
* Adding information to `submitEgg` action for the egg sorting game
* Adding integration with the Portal. If launched from an activity there, the student and classroom IDs are now pulled out of the URL.
* ITS now hints after a student has bred two drakes without completing a challenge. Functionally, this means that after a single reset, the 'reset' and 'submit' buttons to the same thing
Turns out implementing the last bullet point was simpler than expected- I gave `resetGametes` a flag to optionally increment the number of moves, and check `moves` when the 'reset' button is hit.
> ITS Updates

- src/code/components/basket-set.js
- src/stylus/fablevision/fv-egg-sort-game.styl
Another small fix- placing a separate div over the baskets so their click regions don't overlap as they did previously
> Fixing #143585545: click area of baskets is incorrect

- src/code/actions.js
- test/actions/submit-drake.js
A small fix if you wouldn't mind taking a look @kswenson! Trudi noticed that dialog boxes aren't centered on the screen, and may move off entirely on smaller screens. 
I realized the issue is that the dialog boxes have a static offset from the top which isn't scaled, because it's not in the challenge container. I removed the offsets, so now the default `50%` is used. The fix looks fine, but there's a comment in the code that made me want a second pair of eyes:
```
// we use some pseudo random coords so nested modals
// don't sit right on top of each other.
````
I don't want these modals to get covered up, but in this case I'm fairly sure that won't happen.
> Moving dialog boxes to center of screen

- src/code/utilities/trial-generator.js
- src/resources/authoring/gv2.json
- test/utilities/trial-generator.js
For early genome challenges, it was possible for the target drake to match the initial drake exactly. To fix this, I changed the `trialGenerator` for one of the levels, and tweaked the `all-combinations` generation code. Now, it tries up to 100 times to generate 2 drakes with different phenotypes.
I'll admit, the randomization schemes have never been totally clear to me- I'm not sure who worked on each one. Does this seem like a reasonable change? As for the other genome challenges, I believe they avoid duplicates by more specifically outlining each trial.
> Changing initial drake generation to make sure it does not match the target drake

- src/code/actions.js
- src/code/components/gamete-pen.js
- src/code/containers/fv-challenge-container.js
- src/code/containers/navigation.js
- src/code/reducers/helpers/load-state-from-authoring.js
- src/code/reducers/index.js
- src/code/templates/fv-genome-challenge.js
- src/code/templates/genome-challenge.js
- src/resources/authoring/gv2.json
- src/stylus/fablevision/fv-gene-label.styl
- test/templates/egg-game.js
- test/templates/genome-challenge.js
Hi @sfentress! I added two new levels which allow students to play with color in a Genome Challenge. Those changes were small, but the level spec required some more involved updates I'd appreciate your feedback on.
For the first new level, students have to match 5 target drakes over 5 trials - one each of 5 colors, in a random order. For the second level, students match 3 drakes, picking out of the 5 different colors at random. To accomplish this, I added a new `numTrials` field to the authoring doc and state, which allows you to specify any number of trials, and then choose a random subset of them (3 out of a possible 5, in this case). It actually simplified some pieces of code throughout the project.
Let me know what you think!
> Color levels and randomization changes

- src/code/containers/fv-challenge-container.js
- src/code/fv-components/bottom-hud.js
- src/code/reducers/helpers/load-state-from-authoring.js
- src/code/templates/clutch-game.js
- src/code/templates/fv-genome-challenge.js
- src/code/utilities/lang/en-us.js
- src/resources/authoring/gv2.json
- src/stylus/fablevision/bottom-hud.styl
Hi @sfentress! This is a smaller PR to add a moves counter to Genome Challenge and Clutch Breeding levels. Now, the number of `goalMoves` can be calculated on a per-template basis, or through the authoring document. 
Based on future discussions about randomness, we might need logic to dynamically compute minimum moves for complex situations, but I figured this was simplest for now. Let me know what you think!
> Adding moves counter to genome challenge and clutch game templates

- gulp/tasks/geniblocks-js-task.js
- src/code/app.js
This makes Travis not deploy branches if `geniverse.js` fails to build.
This can be seen in the failing Travis build here
https://travis-ci.org/concord-consortium/geniblocks/builds/244612757
and the successful Travis build here
https://travis-ci.org/concord-consortium/geniblocks/builds/244618535
> Gulp fails loudly

- src/code/action-types.js
- src/code/actions.js
- src/code/app.js
- src/code/middleware/state-save.js
- src/code/reducers/gems.js
- src/code/utilities/url-params.js
- src/index.html
- test/actions/start-session.js
I could have sworn I opened a PR for this yesterday, but I must not have pulled the trigger...in any case, here's what I've accomplished for state saving, with the [schema update suggested by Sam](https://gist.github.com/sfentress/b0b83103d2109ec287160511801c96e2). I didn't understand the `stateVersion` piece of the key so I left it out, but it might be worth talking over that more.
We interact with Firebase in two different places: 
1) When a session begins, we check if the user has any stored data. If so, we load it into the state. At this point, we also check if this version of the authoring document is stored in Firebase, and if not, we load it in.
2) When a challenge ends, a new piece of middleware updates the user's state in Firebase.
I'm sure there are more clever ways to have …
> Firebase State Saving

- src/code/action-types.js
- src/code/actions.js
- src/code/components/notifications.js
- src/code/containers/challenge-container-selector.js
- src/code/containers/challenge-container.js
- src/code/containers/fv-challenge-container.js
- src/code/fv-components/bottom-hud.js
- src/code/fv-components/navigation-dialog.js
- src/code/middleware/router-history.js
- src/code/modules/notifications.js
- src/code/reducers/challenge-errors.js
- src/code/reducers/helpers/load-state-from-authoring.js
- src/code/reducers/index.js
- src/code/reducers/modal-dialog.js
- src/code/utilities/authoring-utils.js
- src/resources/authoring/gv2.json
- src/stylus/fablevision/rooms.styl
- src/stylus/notifications.styl
- test/actions/egg-accepted.js
- test/actions/egg-rejected.js
- test/actions/submit-drake.js
This adds 
1. The Mission Control screen, visible at `/#home`
2. Loading mission control by default if you navigate to `/`
3. Start-mission dialog if you navigate to home and at at the start of a mission, with no challenges solved (counting blank gems as "solving" a mission)
4. Middle-mission dialog if you enter the mission control and you have > 1 gems in the mission (for most users, this will only accessible if they load the game with saved-state, because currently there is no way to navigate to the MC except by editing the url)
5. On the Victory screen, the Continue button will now either open the Navigation if there are more challenges in a mission, or go back to MC if there aren't
6. If they go back to the MC via the Victory screen, they are presented with End-mission dialog before …
> Mission Control

- src/code/reducers/gems.js
A previous commit allowed missions to be completed out of order by removing undefined mission arrays, which break Firebase storage. This commit allows challenges to be completed out of order, by setting incomplete challenges to null to allow storage in Firebase.
> Gem is awarded if challenges are completed out of order

- src/code/app.js
- src/code/utilities/progress-utils.js
- src/resources/authoring/gv2.json
A handful of last minute updates and fixes - unfortunately, I needed to undo the Firebase authoring load. For levels where `targetDrakes` is an array of empty objects, nothing is stored in Firebase, so there is only 1 trial. For now, I added all the narration for level 3 back into the authoring document.
> Demo fixes

- src/code/reducers/helpers/load-state-from-authoring.js
- src/code/utilities/progress-utils.js
This allows mission middle dialog to appear again, undoing the previous commit
> Fixing is mission started check

- src/code/components/clutch-view.js
- src/code/fv-components/breed-button.js
- src/code/templates/fv-genome-challenge.js
There were a few places where you could repeatedly submit drakes, overwhelm the ITS feedback, and get all the messages to concat into a dialog that scrolled off the screen. This PR adds short timeouts that disable submissions. Perhaps it would be worth putting this into some kind of HOC in the future
> Slow submissions

- src/code/middleware/state-save.js
Every action the user takes will now save a timestamp to Firebase, in
a new property `stateMeta`, designed to hold the data that does not make
up a user's loadable state.
This data will allow the Dashboard to show what users are currently
active.
@ekosmin could you please take a look at this when you get a chance?
> Save a timestamp of the last action to firebase

- src/code/actions.js
- src/code/middleware/state-save.js
- src/code/migrations/02_convert_gems_to_array.js
- src/code/migrations/index.js
- src/code/reducers/gems.js
- src/code/reducers/helpers/gems-helper.js
- src/code/utilities/progress-utils.js
- test/actions/submit-drake.js
- test/migrations/migrations.js
This updates the `gems` state to contain arrays of gems for each challenge, instead of a single gem. This means that instead of just keeping the last earned gem, we can keep the gem history for each challenge. This allows us to display this history in the dashboard.
Since we are saving `gems` to Firebase, we need to add a migration for all users that have already saved gems, or those users will revert back to the begining.
In adding a migration, it seemed to simplify things to add `stateVersion` to the `state` object itself. That allows us to make a single request to FB to get our data, with the version.
The combination of this and #174 will make our Firebase user data into:
```
{
state: {
< saveable state (gems) >,
stateVersion: 2
},
stateMeta: { 
lastActionTime: t 
},
itsData: < set by …
```
> Save past gems

- package.json
- readme.md
- src/code/reducers/helpers/gems-helper.js
- src/code/utilities/progress-utils.js
@ekosmin This is a one-line change, returning `false` from the function `isMissionLocked`. It seems to work fine, but wanted to check if you have thoughts about doing it this way.
I think in a few months we'll want to have this function back the way it was (perhaps alongside a Firebase property settable from the teacher dashboard), so I wanted to leave it easy to revert.
> Remove gating temporarily

- src/code/fv-components/fv-chromosome-image.js
- src/code/fv-components/fv-gene-label.js
- src/resources/images/arrow.svg
- src/stylus/challenges.styl
- src/stylus/fablevision/fv-chromosome.styl
- src/stylus/fablevision/fv-gene-label.styl
I used css instead of the supplied images to improve rendering and flexibility of layout of drop downs, especially the switch from arrows on the right to left depending on which side the label is positioned. I did not see any samples showing hover highlights for option selection so I improvised with a general grey background, though that can be changed fairly easily.
I wasn't sure how to get to a layout that used the brown background - do any of the current challenges use that layout?
The React Selectize SimpleSelect control did not seem to allow the option to resize the svg arrow that was included in the control so I added a simple arrow.
> Implement css version of FV drop down styling images

- src/code/actions.js
- src/code/components/modal-alert.js
- src/code/components/notifications.js
- src/code/containers/notification-container.js
- src/code/modules/notifications.js
- src/code/reducers/modal-dialog.js
- src/code/utilities/lang/en-us.js
- src/stylus/fablevision/venture-pad.styl
- src/stylus/notifications.styl
- test/actions/egg-accepted.js
- test/actions/show-modal-dialog.js
- test/actions/submit-drake.js
- test/actions/submit-egg.js
When the user has completed a challenge, show a Success message from a character while the new drake is still visible; let the new gem be visible; and block any mouse interaction except moving forward.
https://www.pivotaltracker.com/story/show/154811093
> In-challenge success message

- package.json
- readme.md
- src/resources/authoring/authoring.schema.json
- yarn.lock
Add schema for authoring validation [#157981472]
- add `validate` script to perform authoring validation against schema
There's a lot more that could be done here, but this should be a reasonable starting point. I've fleshed out the schema for the `FVGenomeChallenge`, but the other challenges are currently handled generically. Allele strings and gene lists could be validated with regular expressions, etc.
@dstrawberrygirl pointed out that Visual Studio Code can be configured to [show schema validation errors](https://code.visualstudio.com/docs/languages/json#_mapping-to-a-schema-in-the-workspace) in the editor. My configuration looks like
```
// Associate schemas to JSON files in the current project
"json.schemas": [{
"fileMatch": ["gv-1.json"],
"url": …
```
> Add schema for authoring validation

- src/code/templates/fv-egg-sort-game.js
- src/resources/authoring/authoring.schema.json
- src/resources/authoring/gv-1.json
Note: This PR depends on PR #199. Once that is reviewed/merged this can be rebased to master to simplify review/merge of this PR.
Add detailed FVEggSortGame to schema
Additional schema improvements
- regex for gene list properties
- regex for allele string properties
Add level 6 egg sort challenges
- Challenge 6.2.1 (tail) [#157981278]
- Challenge 6.2.2 (nose spike) [#157981284]
Adjust egg hatch location to avoid jump when fade begins
Fix bug in which egg would sometimes appear briefly back in straw after animating to basket [#158034904]
Fix bug in which end-of-challenge dialog sometimes wouldn't appear [#158034904]
> Level 6 challenges 2.1 and 2.2 (egg sorting)

- package.json
- readme.md
- script/narrative.js
- src/resources/authoring/authoring.schema.json
- src/resources/authoring/gv-1.json
Not seeing a script for exporting the narrative text in the repository, I decided to whip one up. Apparently, another script already exists. @dstrawberrygirl I'm not sure how best to handle this. If you want to add the other script to this PR we can make both available. Or we can decide to merge the two somehow.
In writing and testing the script I encountered and fixed a couple of issues with the authoring document itself, e.g. unused properties and inconsistent challenge naming.
Note: To get the Travis build to complete I had to fix an unrelated bower installation issue that seems to have resulted from some change in the way the React-DnD library is made available through bower. For Geniventure itself, we use npm to install the appropriate version of React-DnD. For some of the older …
> Export narrative text

- src/code/reducers/helpers/load-state-from-authoring.js
- src/resources/authoring/authoring.schema.json
- src/resources/authoring/gv-1.json
Target-matching challenges now provide a means of specifying a minimum number of moves when generating drakes [#158095906].
> Enforce minimum number of moves in target-matching challenges

- package.json
- script/unused.js
Add `unused` script to identify unused templates and challenges in the authoring file [#158160165]
Output:
```
Authoring File: src/resources/authoring/gv-1.json
Git Branch: 157981337-challenges-6.3.x
Export Date: 2018-06-06 17:44:40
Unused templates:
EggGame
EggSortGame
GenomeChallenge
GenomePlayground
Unused challenges:
allele-5drakes-tutorial-original
allele-targetMatch-hidden-armorHorns-original
allele-targetMatch-hidden-simpleColors-original
allele-targetMatch-hidden-simpleDom-original
allele-targetMatch-visible-armorHorns-original
allele-targetMatch-visible-simpleColors-original
allele-targetMatch-visible-simpleDom-original
cell-game-lava-steel-nucleus
clutch-5drakes-intermediateTraits-original
clutch-5drakes-starterTraits-original
eggBreedingBasicChromosomesUnique …
```
> Add `unused` script to identify unused templates and challenges

- src/code/templates/fv-egg-game.js
Fix bug which prevented FVEggGame challenges from working correctly when retrying a challenge
- onResetGametePools() was being called after generation of the gamete pools but before the challenge
@sfentress fixed [#155271461](https://www.pivotaltracker.com/story/show/155271461) in 0b9583a7baa60d1ba58ad05d316272eb0b229916, which was reverted by @dstrawberrygirl in favor of d8a8f6473de220d85df6357d3e6df1b412e0be14 which was intended to fix [#157810891](https://www.pivotaltracker.com/story/show/157810891), but which also caused [#158224594](https://www.pivotaltracker.com/story/show/158224594).
This should fix all three without reintroducing any of the others.
> Fix bug which prevented egg game from working correctly when retrying a challenge

- src/stylus/fablevision/target-drake.styl
This should get the target gizmo in the correct place for all 4.1.x challenges - Firefox still has other issues with layout that are known and tracked, but at least this tackles one of them.
> Fix target drake gizmo

- src/code/reducers/helpers/load-state-from-authoring.js
- src/resources/authoring/gv-1.json
Fix bug in which linked sex-linked genes could result in gratuitous nose spikes [#158535268]
This bug was introduced on 2018-06-06 in commit cba46a4e143086cf8b440d8b17d93d07847d04aa.
Authoring changes resulting from fix of linkedGenes bug
- restore `nose` to list of `linkedGenes` in challenges from which it was recently removed (to avoid the bug)
- removed redundant specification of nose spike gene in challenges in which it is linked
> Fix gene-linking of sex-linked traits

- src/code/middleware/its-log.js
ITS v3 is currently not able to offer correct hints, so this PR is a quick adjustment to disable receiving ITS hints and alerts until the service can be fixed.
> Remove handlers for receiving ITS alerts and hints

- src/code/components/tutorial-view.js
- src/code/templates/clutch-game.js
- src/resources/authoring/tutorial.json
- src/stylus/fablevision/fv-chromosome.styl
Recent layout tweaks have broken tutorial highlight functionality on genome challenges since flex layout elements are not affected by z-index changes. Attempted workaround for this PR is to elevate the closest parent element and then pulse the element being described in the tutorial.
> Adjust highlight for tutorial elements

- src/code/templates/fv-egg-sort-game.js
Fixes https://www.pivotaltracker.com/story/show/158911599
Sex remediation contains no alleles on baskets. This was being automatically marked as incorrect.
> Fix sex remediation in egg-sort game

- src/code/middleware/state-save.js
Replacing nulls with empty array when saving user's state to Firebase hopefully fixes the issue with failing updates - reloading the user at the same challenge will still show null for remediation for those challenges, so this doesn't seem to alter the original data.
> Potential solution to null values in remediationHistory

- src/stylus/notifications.styl
Make end of challenge dialog clickable so users can move on to next challenge [#160618770]
- increase the z-index of the modal message so that it's on top of the VenturePad overlay
@sfentress It would be worth taking a look at the overall set of z-indices in use to make sure that there's an appropriate global ordering.
> Make end of challenge dialog clickable so users can move on to next challenge

- deploy/s3_deploy.sh
Used technique from https://www.topcoder.com/blog/recover-lost-travisci-variables-two-ways/ to recover the contents of the S3_SECRET_KEY environment variable. Then use it to eliminate redundant environment variable definitions.
Note: I'm leaving the definition of S3_SECRET_KEY in place in the Travis settings until we're certain that the replacement is working. It should be removed once that's been verified.
> Use default AWS environment variable names

- src/code/modules/remediation.js
Fixes [#166484061](https://www.pivotaltracker.com/story/show/166484061):
>Within a remediation challenge, navigating to another challenge (e.g. using VenturePad or directly modifying the URL) without completing the challenge leaves Geniventure in a confused state that prevents any subsequent remediation from occurring.
> Clear remediation state on challenge navigation

- src/code/modules/notifications.js
- src/stylus/notifications.styl
[#167663884] Fix bug in which a user-requested connection status message would dismiss the end-of-challenge dialog in remediation, thus preventing the user from being able to exit remediation. The fix here is to add `pointer-events: auto` to the `fv-character` class so that the avatar button (which brings up the connection status message) cannot be clicked while a character is present, i.e. when any dialog message is present.
Also fixed a latent bug found while investigating possible fixes to the previous bug. In the handler for `ADVANCE_NOTIFICATIONS` in the notifications reducer, an ill-formed state object could be returned.
@dstrawberrygirl I originally assigned this to you for review, but since you were out I reviewed it synchronously with Matt.
> Fix bug which could prevent exiting remediation

- src/code/components/clutch-view.js
- src/code/components/notifications.js
- src/code/modules/remediation.js
- src/code/reducers/helpers/load-state-from-authoring.js
- src/stylus/notifications.styl
This adds breeding and sibling remediation.
As usual, the remediation generator is fairly special-cased and wordy. It attempts to generalize as much as possible, but has to account for the following situations:
1. Straight breeding or sibling (submit parents) challenge
2. One changeable parent or two (straight breeding only)
3. Traits or ITS concepts that are not plain dominance/recessive (sometimes special-cased by concept, sometimes by trait)
> Breeding and siblings remediation
